spring:
  cloud:
    gateway:
      routes:
        - id: retail-account
          uri: http://localhost:8002/
          predicates:
            - Path=/digi/retailbank/v1/**
          filters:
            - name: Hystrix
              args:
                name: retail-account
                fallbackUri: forward:/fallback/accountFallback
            - name: AccountPreFilter
            - name: AccountPostFilter
